server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    password: ''
    h2:
      console:
        enabled: 'true'
        path: /h2-console
  jackson:
    deserialization:
      fail-on-unknown-properties: true