INSERT INTO tb_anime (name) VALUES ('Maria');
INSERT INTO tb_anime (name) VALUES ('Joao');
INSERT INTO tb_anime (name) VALUES ('Leonard');
INSERT INTO tb_anime (name) VALUES ('Sheldon');
INSERT INTO tb_anime (name) VALUES ('Howard');
INSERT INTO tb_anime (name) VALUES ('Raj');
INSERT INTO tb_anime (name) VALUES ('Penny');
INSERT INTO tb_anime (name) VALUES ('Stuart');
INSERT INTO tb_anime (name) VALUES ('Amy');